apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test111-init
spec:
  params:
    - name: git-revision
      value: master
  pipelineRef:
    name: test111
  serviceAccountName: pipeline
  workspaces:
    - name: source-dir
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: sonar-settings
      secret:
        secretName: sonarqube-secret-token
    - configMap:
        name: maven-settings
      name: maven-settings